### ISSUE TITLE
Content Ideas

### ISSUE THREAD

**Issue by Sean-Der** [pion/website#21]
Anyone feel free to edit this, but here are my ideas for far for what I would like to write.

------
### Why Pion
Intro article on what make Pion a good choice, hit on some of these topics

* Written in Go (Easy deployment, quick to deploy, quick to code, works everywhere `mobile and servers` and modern tooling friendly)
* Beginner Friendly (Examples for common use cases, good documentation)
* Strong community (Slack and barrier to contribution is very slow)
* Written by devs for devs (We were frustrated by other solutions, wrote something for our problems)
* Slim dependencies (SCTP, DTLS and SCTP we implemented. Very easy to audit and learn)
* Used in real world already (Can we cite some companies? Proud to be used by...?)

### The path towards an auto-scaling SFU
One of the things I wanted to write and wasn't possible, but now it is possible with Pion.

Talk about issues, and how we plan to solve them
* Sharing keying material
* Having SFUs peer
* Scaling up and down (and moving peers between servers)

### Building an application with Pion
@Antonito recently built a project with Pion, would love to hear about the things he found frustrating/enlightening. 

### Decentralized Signaling
@cretz wrote this really cool signaler via IPFS, would love to get a guest post out of it

### IPFS + WebRTC
Would love to understand IPFS more, and how WebRTC (Pion) will change lots of things for it

### What Can WebRTC Solve for me?
I want to help people understand `What can WebRTC solve for me` we should itemize out everything it can solve.

* Allow two peers to communicate
* Internet setup doesn't matter (WebRTC can traverse firewalls and NATs)
* Bi-directional exchange of audio/video. Arbitrary number of streams
* Bi-directional exchange of text/binary. Arbitrary number of streams

### WebRTC fundamentals 
Talk about how the internet creates all these problems, and we solve each part.

* How do I know who I want to talk too, and what we want to talk about *Exchange IPs via SDP*
* How does the communication happen
  - Host Candidates
  - Srflx candidates
  - Relay candidates
* How do we packetize media, and handle loss
* How do we packetize data, and handle loss

### Page for each part of the stack
Summation of what it does (and why) with links to RFCs
* [ ] ICE
* [ ] STUN
* [ ] TURN
* [ ] SCTP
* [ ] DTLS
* [ ] SRTP
* [ ] RTP
* [ ] RTCP
* [ ] SDP

**Comment by backkem** [comment]
The history of real-time communication
https://www.youtube.com/watch?v=av4KF1j-wp4

**Comment by backkem** [comment]
Unreliable data channels for real-time info like:
- Game position updates
- Stock tickers
- ...
