### ISSUE TITLE
Built with Pion page

### ISSUE THREAD

**Issue by Sean-Der** [pion/website#25]
We should create a built with Pion page that demos everything people have built with Pion so far (and encourage people to add their companies and open source projects to it)

**Comment by backkem** [comment]
It would also be awesome to write (guest) blog posts about these projects. If we have a project 101, reason for using (pions/)WebRTC and some learnings we can play around with the product (if public) and write articles about that.

cc @hugoArregui, @chrisprobst, @albrow, @mjmac, @maxmcd, @calebdoxsey

**Comment by hugoArregui** [comment]
I been thinking on writing some example with the things I'm doing in a pure pion fashion. I can use as a reference to detect issues, discuss the API and it may serve as a test case too. Maybe we can start from that and write an article if you guys found it interesting.

**Comment by backkem** [comment]
That sounds great! Let us know if you need help. We're happy to do the writing if anyone doesn't have the time or it's not their thing.
I'd also love to feature your communication server (since you mentioned it being generic) and write about your experience using unreliable data channels to send real-time data to browsers if/when you can share your findings.

**Comment by chrisprobst** [comment]
We are also planning to publish a blog post series about our SDK development and especially about Pions. In our industry the Go-approach is very unique and actually gives us a lot of flexibility. We already have a Marketing plan but we have not published any posts yet. I think it would be great to cross-link between this project and our blog posts and also maybe just embed our posts here. We will reach out when we are done :-)

**Comment by backkem** [comment]
We can link to [libp2p/go-libp2p-webrtc-direct](https://github.com/libp2p/go-libp2p-webrtc-direct) without using the libp2p logo.
