### ISSUE TITLE
whether it can be used by android or ios apps?

### ISSUE THREAD

**Issue by culturer** [pion/website#26]
I need a rtc system to make  app's  audio or video function.But I don't know whether I can use it .

**Comment by chrisprobst** [comment]
@Sean-Der Thank you very much for this kind response and the great work in general. Don't get me wrong, we are totally fine with the remaining issues. I mean WebRTC in pure Go, how awesome is that :-) Regarding filing bugs, I'm afraid you are right, we could have communicated more about our experience. But to be honest, most issues we have encountered are already filed as bugs :-) (Which is good!)

**Comment by manwithsteelnerves** [comment]
How stable are the libraries now on mobile? can someone give insights on using pion on ios and android platforms?

**Comment by Sean-Der** [comment]
Hey @manwithsteelnerves 

Developers are using it in mobile. It depends on what you are trying to build. I would bring this up in [Slack](https://pion.ly/slack) if you want to have a conversation with the developers.
